spring:
  datasource:
    url: jdbc:mysql://geeson.iptime.org:53306/order_db
    username: root
    password: rootpass^^*
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
grpc:
  server:
    reflection-service-enabled: false
    port: 6565
uuid:
  node-id: ${NODE_ID:1}